site_name: "PYV game engine: the official docs"
site_url: https://gaudiatech.github.io/pyved-engine/
repo_url: https://github.com/gaudiatech/pyved-engine


nav:
  - 'index.md'
  - 'Showcase.md'
  - 'Entity Component System':
    - 'Entity Component System/A bit of theory.md'
    - 'Entity Component System/ECS examples.md'
  - 'Other Patterns':
    - 'Other patterns/Event based programming.md'
    - 'Other patterns/MVC examples.md'
    - 'Other patterns/Actor Based.md'
  - 'Game Tutorials':
    - 'GameTutorials/Breakout.md'
    - 'GameTutorials/Platformer.md'
    - 'GameTutorials/Roguelike.md'
  - 'Reference':
    - 'Reference/Using sprites.md'
    - 'Reference/Gamestates.md'
  - 'ShareYourGames.md'


theme:
  name: material
  font: false
  icon:
    logo: material/space-invaders


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gaudiatech/pyved-engine
      name: Pyved-engine on Github


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences


plugins:
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
  
      languages:
        en:
          name: English
          build: true
        fr:
          name: Français
          build: true
          site_name: "Documentation pour PYV: moteur de jeu"

      nav_translations:
        fr:
          Bidule: bidule.fr
          Topic1: Sujet1
          Topic2: Sujet2
